### ISSUE TITLE
Less dramatic log messages when running a one-node cluster

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-hazelcast-plugin#13]
When Openfire runs a cluster of one node, the execution of every cluster task leads to a logged warning, like this:

> 2019-02-21 09:01:48,024 WARN  [pool-19-thread-1] ClusteredCacheFactory.java:346 - No cluster members selected for cluster task com.example.MyClusterTask

Not only does this quickly fill up the logs (typical usage pattern will start many cluster tasks), logging it as a warning seems excessive.

**Comment by GregDThomas** [comment]
Reduced to debug level
