### ISSUE TITLE
Stop changing the XMPPServer NodeID

### ISSUE THREAD

**Issue by GregDThomas** [igniterealtime/openfire-hazelcast-plugin#19]
The Hazelcast plugin changes the XMPPServer NodeID every  time a node joins a cluster, and again when it leaves. 

As the NodeID is frequently used as a key to maps, etc. it would make more sense for the NodeID to never change.

**Comment by guusdk** [comment]
A note to future readers: the Hazelcast-reported nodeID and the nodeID as used by Openfire (which will both show up in the same debug log) will have _different_ values! I didn't realize this until after spending an hour debugging things.

Additionally, the Hazelcast nodeID will change (eg: when a node rejoins the cluster), while the Openfire-provided one is stable (it will remain the same value).

**Comment by guusdk** [comment]
I wonder if we can prevent future confusion by using a different format than UUID for the Openfire-managed NodeID value. Then again, I'm unsure if that's worth the effort.
