### ISSUE TITLE
java.lang.AbstractMethodError when  open Details of Remoteuser on Adminconsole

### ISSUE THREAD

**Issue by mightymop** [igniterealtime/openfire-hazelcast-plugin#28]
With latest Commits on Openfire: "OF-1771 Show software version of connection"
there are some updates to the Clusterplugin needed...
I allways get an java.lang.AbstractMethodError when i try to open de session-details.jsp of a remote user on admin console.

**Comment by guusdk** [comment]
Thanks for catching this. I've created this change (but didn't test it) in the hopes that it prevents the issue you're seeing: https://github.com/igniterealtime/Openfire/pull/1380

**Comment by GregDThomas** [comment]
Confirmed as fixed in https://github.com/igniterealtime/Openfire/pull/1380
