### ISSUE TITLE
Newly created Group Chat Service do not replicates to other Openfire nodes in the cluster

### ISSUE THREAD

**Issue by ernakulgoyal** [igniterealtime/openfire-hazelcast-plugin#30]
Hello There,

I have setup a two node Openfire cluster using Hazelcast Plugin.

I am creating a group chat service from Openfire admin console of Node A.

The newly created service do not replicates on Openfire Node B.
![image](https://user-images.githubusercontent.com/23117949/62513756-b2ddb900-b83a-11e9-813f-d5452f6abf7b.png)

Please suggest if there is any configuration which needs to be made or is it an issue. Since, we are unable to find any literature around this anywhere.

**Comment by ernakulgoyal** [comment]
Hello There,

Just wondering if any one can help on this issue.

**Comment by GregDThomas** [comment]
It's a bug. Once also being discussed at https://github.com/igniterealtime/openfire-restAPI-plugin/issues/30

So it strikes me as a bug in core Openfire, not any of the plugins (OF should take care of distributing state across the cluster).

**Comment by GregDThomas** [comment]
I believe this is now fixed in https://github.com/igniterealtime/Openfire/pull/1479

**Comment by ernakulgoyal** [comment]
Hey @GregDThomas, will it be available with 4.4.2 OF version or Hazelcast Plugin?
Does this fix also includes the 'Cluster Aware' behaviour of configuration changes made in any service?

**Comment by GregDThomas** [comment]
It’s a fix to core Openfire, not the clustering plug-in. The schedule of the releases for that is out of my control, unfortunately.

**Comment by GregDThomas** [comment]
https://github.com/igniterealtime/Openfire/pull/1479

**Comment by GregDThomas** [comment]
Closing this, should be fixed in OF 4.4.2
