### ISSUE TITLE
Openfire version should be listed for each node

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-hazelcast-plugin#47]
I made a boo-boo.

Accidentally, I installed two different versions of Openfire in my cluster (clustering seemed to work just fine).

I had expected that the Admin Console maybe not warn me, but at least show me the version of Openfire running on each cluster node. It currently does not:

![image](https://user-images.githubusercontent.com/4253898/78802765-7ad8d800-79be-11ea-9dbc-287bc926b698.png)

**Comment by GregDThomas** [comment]
Whilst I've never done this, the "zero downtime upgrade procedure" does rely on running mixed-version Openfire cluster during the upgrade. Apparently. So I'm guessing it is/should be supported.

**Comment by guusdk** [comment]
I don't want to imply whether or not that should be supported (above my paygrade). I just suggest to display the version number - or do you think that this would imply that you can run different versions?

To me, it'd be a nice way to quickly get an overview, potentially diagnose issues: "ah, that node is running a different version!"

**Comment by GregDThomas** [comment]
Sorry, should have been clear. Yes, fully support the idea of showing the OF version (and HZ plugin version?) on that screen.

**Comment by guusdk** [comment]
Closing this in favor of adding it into Openfire directly: https://issues.igniterealtime.org/browse/OF-2068
