### ISSUE TITLE
correct way of determining node cluster state

### ISSUE THREAD

**Issue by devillaccc** [igniterealtime/openfire-hazelcast-plugin#57]
ClusterManager#isSeniorClusterMember method returns 'true' until the node in cluster receives 'joinCluster' event. 

Scenario:

- Custom built plugin name 'cltest' deployed with other Openfire plugins and HazelCast
- cltest loads up. Its determining cluster status using ClusterManager.,isClusteringAvailable && ClusterManager.isSeniorClusterMemebr. This condition returns 'true' on all the nodes cluster until each node received 'joinCluster'. 

How to determine cluster state in this situation ?

**Comment by GregDThomas** [comment]
Please use issues for bug reports only, please use the forums at https://discourse.igniterealtime.org/ for these sort of discussions.

However, you may want to look at ClusterManager.isSeniorClusterMemberOrNotClustered()

**Comment by devillaccc** [comment]
Hi Greg, thanks for your response. ClusterManager.isSeniorClusterMemberOrNotClustered() is not available on OF 4.0.2. 

As cluster status is not returned correctly, can this be considered as an issue or defect ?
